Homework 2
================
Gauri Bhatkhande

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(dplyr)
```

## Problem 1

Read the Mr. Trashwheel dataset

``` r
trashwheel_df = 
  read_xlsx("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
            sheet = "Mr. Trash Wheel",
            range = cell_cols("A:N")) %>%
  janitor::clean_names() %>%
drop_na(dumpster)%>%
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

Read precipitation data for 2018 and 2017

``` r
precip_2018 = 
  read_excel(
    "./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)
  
precip_2017 = 
  read_excel(
    "./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    skip = 1
  ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
```

Now combine annual precipitation

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df =
  bind_rows(precip_2018, precip_2017)
  

left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # … with 14 more rows

This dataset contains information from the Mr. Trashwheel trash
collector in Balitimore, Maryland. The dataset contains information on
year, month, trash collected, specific kinds of trash. There are total
344 rows. Additional data sheets include month precipitation data.

## Problem 2

Reading the NYC Transit data from the csv and cleaning it :

``` r
nyc_transit_df =
  read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>%
  select(division:route11, entry, vending, entrance_type, ada)
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
# Converting the entry variable from character to logical  (TRUE, FALSE)
nyc_transit_df$entry =
  ifelse(nyc_transit_df$entry=="YES",TRUE,FALSE )
```

### Short note on the dataset

The given dataset contains the variables: division, line, station\_name,
station\_latitude, station\_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entry,
vending, entrance\_type, ada. So far, I imported the data and read the
data from the csv file usinf read\_csv function. After that, using the
pipe operator I went on to clean the dataset which converted the
variable names to lower snake case. For this purpose, I used a function
(clean\_names) without loading the entire package (janitor). After this,
I selected the required column names specified in the homework question
using the select function and then selecting the variables in the
specified order. In the next step, I converted the entry variable from
character to logical (TRUE, FALSE) using the ifelse function wherein I
change the entry variable from nyc\_transit\_df dataset and assign TRUE
for the values that earlier said “yes” and else - FALSE

The dataset now has 1868 rows and 20 columns.

**Finding number of distinct stations**

``` r
count(distinct(nyc_transit_df, paste(nyc_transit_df$line, nyc_transit_df$station_name)))
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   465

The number of distinct stations are 465

**Finding how many stations are ADA compliant**

``` r
ada_compliant_station = 
  filter(nyc_transit_df, ada==TRUE) %>%
  distinct(paste(line, station_name)) %>%
   count()
```

84 stations are ADA compliant.

**Finding proportion of station entrances / exits without vending allow
entrance**

``` r
total_entry =
  filter(nyc_transit_df, vending=='NO') %>%
  count()

tot_entry_allowed = 
  filter(nyc_transit_df, vending=='NO') %>%
  filter( entry==TRUE) %>%
  count()


proportion = tot_entry_allowed/total_entry

proportion
```

    ##           n
    ## 1 0.3770492

The proportion of station entrances / exits without vending that allow
entrance is 0.37705 or 37.705%
